output "caf_name" {
	value = azurecaf_name.container_registry.result
    description = "The application name generated by the Azure Cloud Adoption Framework."
}

output "id" {
	value = azurerm_container_registry.container_registry.id
    description = "The ID of the Container Registry."
}

output "login_server" {
    value = azurerm_container_registry.container_registry.login_server
    description = "The URL that can be used to log into the container registry."
    sensitive = true
}

output "admin_username" {
    value = azurerm_container_registry.container_registry.admin_username
    description = "The Username associated with the Container Registry Admin account - if the admin account is enabled."
    sensitive = true
}

output "admin_password" {
    value = azurerm_container_registry.container_registry.admin_password
    description = "The Password associated with the Container Registry Admin account - if the admin account is enabled."
    sensitive = true
}
output "application_container_registry" {
  value       = azurerm_container_registry.container_registry
  description = "The Container Registry settings."
  sensitive = true
}