name: Build Docker Container Image

on:
  push:
    # branches:
    #   - main
  workflow_dispatch:
    inputs:
      container:
        description: 'Image Name'
        required: true
        type: choice
        default: 'nginx'
        options:
            - 'alpine'
            - 'debian'
            - 'nginx'
            - 'ubuntu'
      tag:
        description: 'Image Tag'
        required: true
        default: 'latest'
jobs:

  build-image:
    name: Build Docker image
    runs-on: ubuntu-latest
    permissions:
      packages: write
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Login to GitHub Packages
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.14.0
        with:
          context: ./${{ github.event.inputs.container }}
          push: true
          # tags: ghcr.io/${{ github.repository }}:${{ github.sha }}
          tags: ghcr.io/${{ github.event.inputs.container }}:${{ github.event.inputs.tag }}
