name: Build Docker Container Image

on:
  push:
    # branches:
    #   - main
  workflow_dispatch:
    inputs:
      container:
        description: 'Image Name'
        required: true
        type: choice
        default: 'nginx'
        options:
            - 'alpine'
            - 'debian'
            - 'nginx'
            - 'ubuntu'
      tag:
        description: 'Image Tag'
        required: true
        default: 'latest'

env:
  CONTAINER: ./docker

permissions:
  id-token: write
  contents: read
  packages: write

jobs:

  build-image:
    name: 'Build Docker image'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.CONTAINER }}

    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4.2.2

      - name: 'Login to GitHub Packages'
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CONTAINERS_TOKEN }}

      - name: 'Build and Push Docker image'
        uses: docker/build-push-action@v6.14.0
        with:
          context: ${{ env.CONTAINER }}
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ github.event.inputs.container }}:${{ github.event.inputs.tag }}
