name: Pull Docker Container Image

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
    inputs:
      container:
        description: 'Image Name'
        required: true
        type: choice
        default: 'ubuntu'
        options:
            - 'alpine'
            - 'debian'
            - 'nginx'
            - 'ubuntu'

jobs:

  copy-image:
    name: Copy Docker image
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write
    defaults:
      run:
        shell: bash

    steps:

      - name: GitHub Container Registry authentication
        run: echo ${{ secrets.REPO_CLASSIC_TOKEN }} | docker login ghcr.io -username Offlinetech -- G0rjWx56

      # - name: Pull Docker Hub image
      #   run: docker pull ${{ github.event.inputs.container }}

      # - name: Tag the image
      #   run: docker tag ${{ github.event.inputs.container }} ghcr.io/${{ github.actor }}/${{ github.event.inputs.container }}:latest

      # - name: Push image to GitHub Container Registry
      #   run: docker push ghcr.io/${{ github.actor }}/${{ github.event.inputs.container }}:latest