name: Copy Image from GitHub to Azure

on:
  push:
    branches:
      - main

env:
  AZURE_CLIENT_ID: '127da96a-8880-44cb-b28f-052e84de409a'
  AZURE_TENANT_ID: '3df6e774-7c8d-4508-8d07-ffc87c202d4d'
  AZURE_SUBSCRIPTION_ID: 'f160f06a-ac2d-4779-a454-e265dc381318'
  GITHUB_USERNAME: 'offlinetech'
  ACR_NAME: 'crofflinetechcontainerssandbox'
  IMAGE_NAME: 'nginx'
  IMAGE_TAG: 'latest'

defaults:
  run:
    shell: bash

permissions:
  id-token: write
  contents: read
  packages: write

jobs:

  transfer-image:
    name: 'Transfer Docker Image'
    runs-on: ubuntu-latest

    steps:
    # Login to Azure with OIDC
    - name: 'Azure login'
      uses: azure/login@v2.2.0
      with:
        client-id: ${{ env.AZURE_CLIENT_ID }}
        tenant-id: ${{ env.AZURE_TENANT_ID }}
        subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}

    - name: 'Login to GitHub Packages'
      uses: docker/login-action@v3.3.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CONTAINERS_TOKEN }}

    # Pull Image from GitHub Packages
    - name: 'Pull from GHCR'
      run: docker pull ghcr.io/${{ github.repository }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

    # Login in to ACR with OIDC
    - name: 'Login in to ACR'
      run: az acr login --name ${{ env.ACR_NAME }}

    # Push Image to Azure Container Registry
    - name: 'Pull to ACR'
      run: |
        docker tag ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} ${{ env.ACR_NAME }}/image:test
        docker push ${{ env.ACR_NAME }}/image:test
