name: Pull Docker Container Image

on:
  push:
    branches:
      - none
  workflow_dispatch:
    inputs:
      container:
        description: 'Image Name'
        required: true
        type: choice
        default: 'ubuntu'
        options:
            - 'alpine'
            - 'debian'
            - 'nginx'
            - 'ubuntu'

jobs:

  copy-image:
    name: Copy Docker image
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write
    defaults:
      run:
        shell: bash

    steps:

      - name: GitHub Container Registry authentication
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u Offlinetech --password-stdin

      - name: Pull Docker Hub image
        run: docker pull ${{ github.event.inputs.container }}

      - name: Tag the image
        run: docker tag ${{ github.event.inputs.container }} ghcr.io/${{ github.actor }}/${{ github.event.inputs.container }}:latest

      - name: Push image to GitHub Container Registry
        run: docker pull ghcr.io/offlinetech/test:image

  # build-image:
  #   name: Build Docker image
  #   runs-on: ubuntu-latest
  #   permissions:
  #     packages: write
  #   defaults:
  #     run:
  #       shell: bash

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4.2.2
  #     - name: Login to GitHub Packages
  #       uses: docker/login-action@v3.3.0
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GITHUB_TOKEN }}
  #     - name: Build and push Docker image
  #       uses: docker/build-push-action@v6.14.0
  #       with:
  #         context: .
  #         push: true
  #         tags: ghcr.io/${{ github.repository }}:${{ github.sha }}
